const canvas = document.querySelector('#gameCanvas');
const ctx = canvas.getContext('2d');
const W = canvas.width;
const H = canvas.height;
const keys = {};
const player = { x: W / 2, y: H - 75, width: 24, height: 34, speed: 5.2, cooldown: 0, hull: 100, lives: 3, power: 1, invincible: 0 };
const game = { state: 'ready', score: 0, wave: 1, elapsed: 0, spawnTimer: 0, bossTimer: 0, highScore: Number(localStorage.getItem('starfallHighScore') || 0) };
let bullets = [], enemyBullets = [], enemies = [], particles = [], powerups = [], stars = [];
const colors = { orange: '#f0643c', cyan: '#5ae0d0', paper: '#e8e3d7', purple: '#a77cff', yellow: '#ffd166' };

for (let i = 0; i < 90; i++) stars.push({ x: Math.random() * W, y: Math.random() * H, size: Math.random() * 1.8 + .3, speed: Math.random() * 1.8 + .35, alpha: Math.random() * .7 + .2 });

function resetGame() { Object.assign(game, { state: 'playing', score: 0, wave: 1, elapsed: 0, spawnTimer: 0, bossTimer: 0 }); Object.assign(player, { x: W / 2, y: H - 75, hull: 100, lives: 3, power: 1, invincible: 100 }); bullets = []; enemyBullets = []; enemies = []; particles = []; powerups = []; updateHud(); }
function updateHud() { document.querySelector('#score').textContent = String(game.score).padStart(7, '0'); document.querySelector('#wave').textContent = String(game.wave).padStart(2, '0'); document.querySelector('#highScore').textContent = String(game.highScore).padStart(7, '0'); document.querySelector('#hullText').textContent = `${Math.max(0, Math.ceil(player.hull))}%`; document.querySelector('#hullMeter').style.width = `${Math.max(0, player.hull)}%`; document.querySelector('#hullMeter').style.background = player.hull < 35 ? colors.orange : colors.cyan; document.querySelector('#lives').textContent = `${'● '.repeat(Math.max(0, player.lives))}`; document.querySelector('#weaponLevel').textContent = `MK-${['I', 'II', 'III', 'IV'][Math.min(3, player.power - 1)]}`; document.querySelector('#weaponText').textContent = player.power > 1 ? 'MULTI SHOT' : 'SINGLE SHOT'; document.querySelectorAll('.power-dots i').forEach((dot, index) => dot.classList.toggle('active', index < player.power)); }
function showOverlay(type) { const start = document.querySelector('#startOverlay'); const pause = document.querySelector('#pauseOverlay'); start.classList.toggle('is-hidden', type !== 'start'); pause.classList.toggle('is-hidden', type !== 'pause'); }
function fire() { if (player.cooldown > 0 || game.state !== 'playing') return; const offsets = player.power === 1 ? [0] : player.power === 2 ? [-7, 7] : [-10, 0, 10]; offsets.forEach(offset => bullets.push({ x: player.x + offset, y: player.y - 21, width: 4, height: 14, vx: offset * .04, vy: -9, damage: 1 })); player.cooldown = 10; }
function spawnEnemy(type = 'drone') { const types = { drone: { width: 27, height: 25, hp: 2, speed: 1.25, points: 120, color: colors.orange }, scout: { width: 19, height: 19, hp: 1, speed: 2.3, points: 180, color: colors.yellow }, tank: { width: 42, height: 35, hp: 7, speed: .65, points: 500, color: colors.purple } }; const data = types[type]; enemies.push({ ...data, type, x: Math.random() * (W - data.width - 30) + 15, y: -45, phase: Math.random() * 6.28, shot: Math.random() * 100 + 50 }); }
function spawnBoss() { enemies.push({ type: 'boss', x: W / 2 - 64, y: -100, width: 128, height: 66, hp: 80 + game.wave * 18, maxHp: 80 + game.wave * 18, speed: .35, points: 5000, phase: 0, shot: 55 }); }
function hitBox(a, b) { return Math.abs(a.x - b.x) < (a.width + b.width) / 2 && Math.abs(a.y - b.y) < (a.height + b.height) / 2; }
function burst(x, y, color, amount = 12) { for (let i = 0; i < amount; i++) particles.push({ x, y, vx: (Math.random() - .5) * 5, vy: (Math.random() - .5) * 5, life: 1, color }); }
function damagePlayer(amount) { if (player.invincible > 0) return; player.hull -= amount; player.invincible = 70; burst(player.x, player.y, colors.orange, 18); if (player.hull <= 0) { player.lives--; if (player.lives > 0) { player.hull = 100; player.invincible = 160; } else endGame(); } updateHud(); }
function endGame() { game.state = 'over'; game.highScore = Math.max(game.highScore, game.score); localStorage.setItem('starfallHighScore', game.highScore); document.querySelector('#missionStatus').textContent = 'MISSION FAILED'; document.querySelector('#startButton').textContent = 'REDEPLOY'; showOverlay('start'); document.querySelector('#startOverlay .overline').textContent = 'SIGNAL LOST / SECTOR 07'; document.querySelector('#startOverlay h1').textContent = 'MISSION OVER'; document.querySelector('#startOverlay .subtitle').textContent = `SCORE ${String(game.score).padStart(7, '0')}`; updateHud(); }
function update(dt) { if (game.state !== 'playing') return; game.elapsed += dt; game.wave = Math.floor(game.elapsed / 25000) + 1; game.spawnTimer -= dt; game.bossTimer += dt; if (game.spawnTimer <= 0) { const roll = Math.random(); spawnEnemy(roll > .88 ? 'tank' : roll > .62 ? 'scout' : 'drone'); game.spawnTimer = Math.max(230, 720 - game.wave * 35); } if (game.bossTimer > 45000 && !enemies.some(enemy => enemy.type === 'boss')) { spawnBoss(); game.bossTimer = 0; } if (keys.ArrowLeft || keys.a) player.x -= player.speed * dt / 16; if (keys.ArrowRight || keys.d) player.x += player.speed * dt / 16; if (keys.ArrowUp || keys.w) player.y -= player.speed * dt / 16; if (keys.ArrowDown || keys.s) player.y += player.speed * dt / 16; player.x = Math.max(18, Math.min(W - 18, player.x)); player.y = Math.max(28, Math.min(H - 25, player.y)); if (keys[' ']) fire(); player.cooldown = Math.max(0, player.cooldown - dt / 16); player.invincible = Math.max(0, player.invincible - dt / 16); stars.forEach(star => { star.y += star.speed * dt / 16 * (1 + game.wave * .05); if (star.y > H) { star.y = -3; star.x = Math.random() * W; } }); updateObjects(dt); if (Math.floor(game.elapsed) % 2 === 0) updateHud(); }
function updateObjects(dt) { bullets.forEach(bullet => { bullet.x += bullet.vx * dt / 16; bullet.y += bullet.vy * dt / 16; }); bullets = bullets.filter(bullet => bullet.y > -20); enemyBullets.forEach(bullet => { bullet.x += bullet.vx * dt / 16; bullet.y += bullet.vy * dt / 16; if (hitBox(bullet, player)) { bullet.y = H + 20; damagePlayer(18); } }); enemyBullets = enemyBullets.filter(bullet => bullet.y < H + 20); enemies.forEach(enemy => { enemy.y += enemy.speed * dt / 16; enemy.phase += dt / 700; if (enemy.type !== 'boss') enemy.x += Math.sin(enemy.phase) * .7; enemy.shot -= dt / 16; if (enemy.shot <= 0 && enemy.y > 10) { const dx = player.x - enemy.x, dy = player.y - enemy.y, distance = Math.hypot(dx, dy) || 1; enemyBullets.push({ x: enemy.x, y: enemy.y + enemy.height / 2, vx: dx / distance * 2.1, vy: dy / distance * 2.1, width: 5, height: 11 }); enemy.shot = enemy.type === 'boss' ? 34 : 130; } if (hitBox(enemy, player)) { enemy.hp = 0; damagePlayer(enemy.type === 'tank' ? 38 : 24); } }); bullets.forEach(bullet => enemies.forEach(enemy => { if (enemy.hp > 0 && hitBox(bullet, enemy)) { bullet.y = -50; enemy.hp -= bullet.damage; burst(bullet.x, bullet.y, enemy.color, 3); if (enemy.hp <= 0) { game.score += enemy.points; burst(enemy.x, enemy.y, enemy.color, enemy.type === 'boss' ? 40 : 15); if (Math.random() < .12 && enemy.type !== 'boss') powerups.push({ x: enemy.x, y: enemy.y, width: 15, height: 15, vy: 1.5 }); } } })); enemies = enemies.filter(enemy => enemy.hp > 0 && enemy.y < H + 100); powerups.forEach(item => { item.y += item.vy * dt / 16; if (hitBox(item, player)) { player.power = Math.min(4, player.power + 1); item.y = H + 30; updateHud(); } }); powerups = powerups.filter(item => item.y < H + 20); particles.forEach(particle => { particle.x += particle.vx * dt / 16; particle.y += particle.vy * dt / 16; particle.life -= dt / 500; }); particles = particles.filter(particle => particle.life > 0); }
function draw() { ctx.fillStyle = '#071017'; ctx.fillRect(0, 0, W, H); stars.forEach(star => { ctx.globalAlpha = star.alpha; ctx.fillStyle = colors.paper; ctx.fillRect(star.x, star.y, star.size, star.size * 2); }); ctx.globalAlpha = 1; ctx.strokeStyle = 'rgba(90,224,208,.07)'; for (let x = 0; x < W; x += 48) { ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, H); ctx.stroke(); } drawPlayer(); bullets.forEach(bullet => { ctx.fillStyle = colors.cyan; ctx.shadowBlur = 12; ctx.shadowColor = colors.cyan; ctx.fillRect(bullet.x - 2, bullet.y - 8, 4, 14); ctx.shadowBlur = 0; }); enemyBullets.forEach(bullet => { ctx.fillStyle = colors.orange; ctx.beginPath(); ctx.arc(bullet.x, bullet.y, 4, 0, Math.PI * 2); ctx.fill(); }); enemies.forEach(drawEnemy); powerups.forEach(drawPowerup); particles.forEach(particle => { ctx.globalAlpha = particle.life; ctx.fillStyle = particle.color; ctx.fillRect(particle.x, particle.y, 3, 3); }); ctx.globalAlpha = 1; }
function drawPlayer() { if (player.invincible > 0 && Math.floor(player.invincible / 7) % 2 === 0) return; ctx.save(); ctx.translate(player.x, player.y); ctx.fillStyle = colors.cyan; ctx.beginPath(); ctx.moveTo(0, -23); ctx.lineTo(13, 16); ctx.lineTo(5, 12); ctx.lineTo(0, 22); ctx.lineTo(-5, 12); ctx.lineTo(-13, 16); ctx.closePath(); ctx.fill(); ctx.fillStyle = colors.paper; ctx.beginPath(); ctx.moveTo(0, -15); ctx.lineTo(5, 7); ctx.lineTo(0, 4); ctx.lineTo(-5, 7); ctx.closePath(); ctx.fill(); ctx.fillStyle = colors.orange; ctx.fillRect(-5, 18, 4, 9); ctx.fillRect(1, 18, 4, 9); ctx.restore(); }
function drawEnemy(enemy) { ctx.save(); ctx.translate(enemy.x, enemy.y); ctx.fillStyle = enemy.color || colors.orange; if (enemy.type === 'boss') { ctx.fillRect(-enemy.width / 2, -enemy.height / 2, enemy.width, enemy.height); ctx.fillStyle = '#16262a'; ctx.fillRect(-42, -17, 84, 34); ctx.fillStyle = colors.orange; ctx.fillRect(-57, -10, 20, 20); ctx.fillRect(37, -10, 20, 20); ctx.fillStyle = colors.paper; ctx.fillRect(-7, -7, 14, 14); ctx.restore(); ctx.fillStyle = colors.orange; ctx.fillRect(enemy.x - 64, enemy.y - 43, 128 * (enemy.hp / enemy.maxHp), 3); return; } ctx.beginPath(); ctx.moveTo(0, enemy.height / 2); ctx.lineTo(-enemy.width / 2, -enemy.height / 2); ctx.lineTo(0, -enemy.height / 4); ctx.lineTo(enemy.width / 2, -enemy.height / 2); ctx.closePath(); ctx.fill(); ctx.fillStyle = '#1b2529'; ctx.fillRect(-4, -5, 8, 8); ctx.restore(); }
function drawPowerup(item) { ctx.fillStyle = colors.yellow; ctx.shadowBlur = 12; ctx.shadowColor = colors.yellow; ctx.fillRect(item.x - 7, item.y - 7, 14, 14); ctx.shadowBlur = 0; ctx.fillStyle = '#162025'; ctx.font = 'bold 12px monospace'; ctx.fillText('+', item.x - 4, item.y + 4); }
function loop(time) { const delta = Math.min(34, time - (loop.last || time)); loop.last = time; update(delta); draw(); requestAnimationFrame(loop); }
function setStatePlaying() { resetGame(); document.querySelector('#missionStatus').textContent = 'MISSION ACTIVE'; showOverlay('none'); }
document.addEventListener('keydown', event => { keys[event.key] = true; if (event.code === 'Space') event.preventDefault(); if (event.key.toLowerCase() === 'p') { if (game.state === 'playing') { game.state = 'paused'; showOverlay('pause'); document.querySelector('#missionStatus').textContent = 'SYSTEM PAUSED'; } else if (game.state === 'paused') { game.state = 'playing'; showOverlay('none'); document.querySelector('#missionStatus').textContent = 'MISSION ACTIVE'; } } });
document.addEventListener('keyup', event => { keys[event.key] = false; });
document.querySelector('#startButton').addEventListener('click', setStatePlaying); document.querySelector('#resumeButton').addEventListener('click', () => { game.state = 'playing'; showOverlay('none'); document.querySelector('#missionStatus').textContent = 'MISSION ACTIVE'; });
updateHud(); showOverlay('start'); requestAnimationFrame(loop);